[build-system]
requires = ["setuptools", "wheel"]

[tool.poetry]
name = "FileSystemPro"
version = "1.0.0.0"
description = "FileSystem Pro is designed to identify the operating system (OS) on which it`s running and define the paths to various user directories based on the OS."
authors = ["Heitor Bisneto <heitor.bardemaker@live.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
